//
//  RollbarCrashReport.h
//  Rollbar
//
//  Created by Andrey Kornich on 2019-11-27.
//  Copyright © 2019 Rollbar. All rights reserved.
//

#import "DataTransferObject.h"

NS_ASSUME_NONNULL_BEGIN

@interface RollbarCrashReport : DataTransferObject

// Required: raw
// The raw crash report, as a string
// Rollbar expects the format generated by this SDK
@property (nonatomic, nonnull) NSString *raw;

@end

NS_ASSUME_NONNULL_END
